version: '3'
services:
  mysql:
    image: m4t30r0s4as/mysql_elastic:despliegue_dockercompose_mysql_v1
    container_name: mysql_elastic
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: elastic_user
      MYSQL_PASSWORD: admin123
      MYSQL_DATABASE: elastic_db
    volumes:
      - ./data/:/docker-entrypoint-initdb.d/

  elasticsearch:
    image: m4t30r0s4as/elasticsearch:despliegue_dockercompose_elasticsearch_v1
    container_name: elasticsearch
    environment:
      discovery.type: "single-node"
      bootstrap.memory_lock: "true"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      xpack.security.enabled: false
      xpack.security.authc.api_key.enabled: true
      xpack.monitoring.collection.enabled: true
      xpack.security.enrollment.enabled: true
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ./volumes/elasticsearch:/usr/share/elasticsearch/data
    logging:
        driver: "json-file"
        options:
            max-size: "10k"
            max-file: "10"
      
  
  kibana:
    image: m4t30r0s4as/kibana:despliegue_dockercompose_kibana_v1
    container_name: kibana
    environment:
      - "ELASTICSEARCH_URL=[http://localhost:9200]"
      - "SERVER_NAME=127.0.0.1"
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
