FROM m4t30r0s4as/elasticsearch:despliegue_dockerfile_elasticsearch_v1

ARG NAME=elasticsearch

EXPOSE 9200:9200
EXPOSE 9300:9300


ENV discovery.type="single-node"
ENV bootstrap.memory_lock="true"
ENV ES_JAVA_OPTS="-Xms512m -Xmx512m"
ENV xpack.security.enabled=false
ENV xpack.security.authc.api_key.enabled=true
ENV xpack.monitoring.collection.enabled=true
ENV xpack.security.enrollment.enabled=true

VOLUME [ "elastic_data:/usr/share/elasticsearch/data" ]